# Generated by Django 5.2.3 on 2025-06-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chathistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
